### ISSUE TITLE
Data Export

### ISSUE THREAD

**Issue by chrtannus** [cytoscape/iregulon-webapp#10]
Add these files to the download zip, under the `data` directory:

- [ ] The iRegulon results, as a `.txt` file (TSV format)[^1]
- [ ] The query parameters, including the "hidden" default ones (e.g. query gene names, organism, ranking parameters, etc), as a `.txt` file (TSV format, `parameter-name[\t]value`)[^2] -- see #2 and #3
- [ ] An `IRF.gz` file that can be used to load the results in the Cytoscape app--see the **Load** and **Save** buttons in the Cytoscape app's **Results Panel**:
  <img width="555" alt="iregulon-app-buttons" src="https://github.com/user-attachments/assets/24cddf51-2e3f-488a-add6-d169dd91b1e4">

[iregulon-results.txt](https://github.com/user-attachments/files/17234746/iregulon-results.txt)

[^1]: The format of the iRegulon results is TSV, but it includes gene names in the same "columns", where each gene is separated by `;`. I don't know if we should just export the raw results (see attached file) or denormalize these list values (e.g. target, rank) in separate TSV files. I'm not sure which is more convenient for the user, but the raw iRegulon format is probably the better choice.
[^2]: Just like in the iRegulon results, the query genes must be separated by `;`.

**Comment by mikekucera** [comment]
I was thinking of rebuilding the iregulon results from the stored json. But its much easier to just store the entire results as a string in mongo, then return it as-is when exporting. This uses more storage space, but I honestly don't think it will be a problem. We could always delete them manually if it ever came to it.

**Comment by mikekucera** [comment]
For the query parameters, is that just whats sent to the service here?
https://github.com/cytoscape/iregulon-webapp/blob/main/src/server/routes/api/create.js#L35

Are they ever sent back from the service? It seems they will have to be stored in memory until the service job is complete, or fails or times out?

**Comment by chrtannus** [comment]
Saving the raw (string) iRegulon results in mongo sounds like a good idea.

Yes, those should be all the parameters for the main iRegulon query. But remember that the _Metatargetome Query_ will have different parameters -- see #3

The parameters are not sent back from the iRegulon service, so they do have to be saved in memory until the job is complete.

**Comment by mikekucera** [comment]
Christian, the end of the IRF file that was output from the iRegulon app looks like this...
I don't know what these parameters mean or where they come from. The app needs them or else the file can't be imported. Do you have any idea where this data comes from or if its safe to hard-code any of it?

```xml
<eScore>3.0</eScore>
<thresholdForVisualisation>5000</thresholdForVisualisation>
<rocThresholdAUC>0.03</rocThresholdAUC>
<speciesNomenclature>
  <code>1</code>
</speciesNomenclature>
<iRegulonType>PREDICTED_REGULATORS</iRegulonType>
<name>hypoxia_geneset.txt</name>
<motifCollection>10K (9713 PWMs)</motifCollection>
<trackCollection>1120 ChIP-seq tracks (ENCODE raw signals)</trackCollection>
<minOrthologous>0.0</minOrthologous>
<maxMotifSimilarityFDR>0.001</maxMotifSimilarityFDR>
<isRegionBased>false</isRegionBased>
<motifRankingsDatabase>
  <code>hg19_tss_centered_10kb_7sp_mc_v6</code>
  <name>20kb centered around TSS (7 species)</name>
  <delineationDefault>
    <code></code>
    <name></name>
  </delineationDefault>
  <NESvalue>3.0</NESvalue>
  <AUCvalue>0.03</AUCvalue>
  <visualisationValue>5000</visualisationValue>
</motifRankingsDatabase>
<trackRankingsDatabase>
  <code>hg19_tss_centered_10kb_chip_v1</code>
  <name>20kb centered around TSS (ChIP-seq-derived)</name>
  <delineationDefault>
    <code></code>
    <name></name>
  </delineationDefault>
  <NESvalue>3.0</NESvalue>
  <AUCvalue>0.03</AUCvalue>
  <visualisationValue>5000</visualisationValue>
</trackRankingsDatabase>
<overlap>-1.0</overlap>
<delineation/>
<upstream>-1</upstream>
<downstream>-1</downstream>
<attributeName>name</attributeName>
```

**Comment by mikekucera** [comment]
The PR was merged

**Comment by mikekucera** [comment]
I should mention that the `.irf` file can't be imported with Cytoscape 3.10.X. Theres some kind of module error that occurs during XML parsing, probably having to do with the version of Java 3.10 uses.

```
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:820)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:350)
	at persistence.PersistenceUtilities.loadResultsFromXML(Unknown Source)
	at view.actions.LoadResultsAction.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:129)
	at java.desktop/java.awt.MenuItem.processActionEvent(MenuItem.java:692)
	at java.desktop/java.awt.MenuItem.processEvent(MenuItem.java:651)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:379)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:367)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.lang.reflect.InvocationHandler java.lang.reflect.Proxy.h accessible: module java.base does not "opens java.lang.reflect" to unnamed module @4148ed15
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:39)
	at com.thoughtworks.xstream.converters.extended.DynamicProxyConverter.<clinit>(DynamicProxyConverter.java:42)
```
